api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/src/Controller']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        # api_keys:
            # cookieAuth:
            #     name: "PHPSESSID"
            #     type: "header"
        api_keys:
            bearerAuth:
                name: Authorization
                type: header
