lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: email
    token_ttl: 3600 # token TTL in seconds, defaults to 1 hour
    # api_platform:
    #     check_path: /api/login_check
    #     username_path: email
    #     password_path: security.credentials.password
