sonata_admin:
    title: 'Artensia'
    title_logo: '/images/artensia_logo.png'
    options:
        skin: 'skin-black'
    dashboard:
        blocks:
            # - { type: sonata.admin.block.admin_list, position: left }
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [dashboard]
        groups:
            dashboard:
                label: 'ADMIN'
            user_block:
                label: 'USERS'

# sonata_block:
#     blocks:
#         sonata.admin.block.admin_list:
#             contexts: [admin]

# The value "skin-toto" is not allowed for path "sonata_admin.options.skin". Permissible values: "skin-black", "skin-black-light", "skin-blue", "skin-blue-light", "skin-green", "skin-green-light", "skin-purple", "skin-purple-light", "skin-red", "skin-red-light", "skin-yellow", "skin-yellow-light"